config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'resources#index'
  get 'presentation', to: 'pages#presentation'
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :admin, only: [:index]
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :edit, :update, :new, :create]
    resources :projets, only: [:index, :show, :edit, :update, :new, :create]
    resources :categories, only: [:index, :show, :edit, :update, :new, :create]
    resources :formats, only: [:index, :show, :edit, :update, :new, :create]
    resources :resources, only: [:index, :show, :edit, :update, :new, :create]
  end
  resources :resources, only: [:index]
  resources :resources, only: [:show], param: :slug
  resources :qrcodes, only: [:show], param: :slug
  resources :qrcodes, only: [:index]
end

app/views/admin/index.erb
<div class="row justify-content-md-center">
  <div class="col-lg-8 col-md-12">
    <div class="alert alert-primary border my-4" role="alert">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item active" aria-current="page"><%= link_to 'Administration', admin_index_path %></li>
        </ol>
      </nav>
    </div>

    <ul class="list-group mb-4">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Utilisateurs', admin_users_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= User.count %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Étiquettes', admin_labels_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= Label.count %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Projets', admin_projets_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= Projet.count %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Catégories', admin_categories_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= Category.count %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Formats', admin_formats_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= Format.count %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h5 class="m-0"><%= link_to 'Ressources', admin_resources_path, class: 'text-decoration-none text-dark' %></h5>
        <span class="badge bg-primary rounded-pill"><%= Resource.count %></span>
      </li>
    </ul>
  </div>
</div>