config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'resources#index'
  get 'presentation', to: 'pages#presentation'
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :admin, only: [:index]
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :edit, :update, :new, :create]
    resources :projets, only: [:index, :show, :edit, :update, :new, :create]
    resources :categories, only: [:index, :show, :edit, :update, :new, :create]
    resources :formats, only: [:index, :show, :edit, :update, :new, :create]
    resources :resources, only: [:index, :show, :edit, :update, :new, :create]
  end
  resources :resources, only: [:index]
  resources :resources, only: [:show], param: :slug
  resources :qrcodes, only: [:show], param: :slug
  resources :qrcodes, only: [:index]
end

app/views/admin/resources/edit.erb
<div class="row justify-content-md-center">
  <div class="col-lg-8 col-md-12">
    <div class="alert alert-primary border my-4" role="alert">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item"><%= link_to 'Administration', admin_index_path %></li>
          <li class="breadcrumb-item"><%= link_to 'Ressources', admin_resources_path %></li>
          <li class="breadcrumb-item "><%= @resource.slug %></li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-lg-5 col-md-6">
    <%= form_with(model: @resource, url: admin_resource_path) do |f| %>
    <div class="card">
      <h5 class="card-header">Edition d'une ressource</h5>
      <div class="card-body">
        <%= render 'shared/errors', object: @resource %>

        <%= f.label 'Étiquette', class: 'mt-1' %>
        <%= f.select :label_id, Label.order(:name).all.map {|l| [l.name, l.id] }, {} , { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1', required: :required }%>

        <%= f.label 'Projet', class: 'mt-1' %>
        <%= f.select :projet_id, Projet.order(:name).all.map {|p| [p.name, p.id] }, {}, { class: 'form-select mt-1', required: :required }%>

        <%= f.label 'Catégorie', class: 'mt-1' %>
        <%= f.select :category_id, Category.order(:name).all.map {|c| [c.name, c.id] }, {}, { class: 'form-select mt-1', required: :required  }%>

        <%= f.label 'Format', class: 'mt-1' %>
        <% formats_options = Format.order(:group).distinct.pluck(:group).map { |g| [g, Format.where(group: g).map {|fo| [fo.name, fo.id, {'data-code': fo.code, selected: fo.id == @resource.format_id }] }] } %>
        <%= f.select :format_id, grouped_options_for_select(formats_options), {}, { class: 'form-select mt-1', required: :required }%>

        <%= f.label 'Langue', class: 'mt-1' %>
        <% languages_options = LanguageList::ALL_LANGUAGES.map { |l| ["#{l.iso_639_3} - #{l.name}", l.iso_639_3.upcase] }.append(['xxx - Unknown', 'xxx']) %>
        <%= f.select :code_language, languages_options, { include_blank: true }, { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1' }%>


        <%= f.label 'Version', class: 'mt-1' %>
        <%= f.select :version, (1..99), { selected: @resource.version || 1 }, { class: 'form-select mt-1', required: :required }%>

        <div class="ressource-translation d-none">
          <%= f.label 'Traduction', class: 'mt-1' %>
          <%= f.text_field :translation, class: 'form-control mt-1', minlength: 2, required: :required  %>
          <%= f.button :submit, class: 'btn btn-success mt-3' do %>
          <i class="fas fa-check"> Valider</i>
          <% end %>
        </div>
        <div class="ressource-upload">
          <%= f.label 'Fichier', class: 'mt-1' %>
          <%= f.file_field :file, class: 'form-control mt-1' %>
          <%= f.button :submit, class: 'btn btn-success mt-3' do %>
          <i class="fas fa-check"> Valider</i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/resources/index.erb
<div class="row justify-content-md-center admin mb-5">
  <div class="col-lg-10 col-md-12">
    <div class="alert alert-primary border mt-4" role="alert">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item"><%= link_to 'Administration', admin_index_path %></li>
          <li class="breadcrumb-item active"><%= link_to 'Ressources', admin_resources_path %></li>
        </ol>
      </nav>
    </div>

    <%= link_to new_admin_resource_path, class: 'btn btn-success mb-3' do %>
      <i class="fas fa-plus-square"> Créer une ressource</i>
    <% end %>

    <table class="table table-striped border mb-4">
      <thead class="bg-primary text-light border border-primary">
        <tr>
          <th scope="col"></th>
          <th scope="col">Identifiant</th>
          <th scope="col">Projet</th>
          <th scope="col">Catégorie</th>
          <th scope="col">Format</th>
          <th scope="col">Étiquette</th>
          <th scope="col">Langue</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @resources.order(created_at: :desc).each_with_index do |resource, i| %>
        <tr>
          <th><%= i + 1 %></th>
          <td><%= resource.slug %></td>
          <td><%= resource.projet.try(:name) || 'Ø' %></td>
          <td><%= resource.category.try(:name) || 'Ø' %></td>
          <td><%= resource.format.try(:name) || 'Ø' %></td>
          <td><%= resource.label.name %></td>
          <td><%= resource.code_language %></td>
          <td>
            <%= link_to resource_path(resource.slug), class: 'btn btn-sm btn-secondary' do %>
              <i class="fas fa-eye"></i>
            <% end %>
            <%= link_to admin_resource_path(resource), class: 'btn btn-sm btn-primary' do %>
              <i class="fas fa-search"></i>
            <% end %>
            <%= link_to edit_admin_resource_path(resource), class: 'btn btn-sm btn-warning' do %>
              <i class="fas fa-pencil-alt"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="text-center">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>

  </div>
</div>

app/views/admin/resources/new.erb
<div class="row justify-content-md-center">
  <div class="col-lg-8 col-md-12">
    <div class="alert alert-primary border my-4" role="alert">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item"><%= link_to 'Administration', admin_index_path %></li>
          <li class="breadcrumb-item active"><%= link_to 'Ressources', admin_resources_path %></li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-lg-5 col-md-6">
    <%= form_with(model: @resource, url: admin_resources_path) do |f| %>
    <div class="card mb-5">
      <h5 class="card-header">Crée une ressource</h5>
      <div class="card-body">
        <%= render 'shared/errors', object: @resource %>

        <%= f.label 'Étiquette', class: 'mt-1' %>
        <%= f.select :label_id, Label.order(:name).all.map {|l| [l.name, l.id] }, {} , { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1 rounded', required: :required }%>

        <%= f.label 'Projet', class: 'mt-1' %>
        <%= f.select :projet_id, Projet.order(:name).all.map {|p| [p.name, p.id] }, {}, { class: 'form-select mt-1', required: :required }%>

        <%= f.label 'Catégorie', class: 'mt-1' %>
        <%= f.select :category_id, Category.order(:name).all.map {|c| [c.name, c.id] }, {}, { class: 'form-select mt-1', required: :required  }%>

        <%= f.label 'Format', class: 'mt-1' %>
        <% formats_options = Format.order(:group).distinct.pluck(:group).map { |g| [g, Format.where(group: g).map {|fo| [fo.name, fo.id, {'data-code': fo.code, selected: fo.id == @resource.format_id }] }] } %>
        <%= f.select :format_id, grouped_options_for_select(formats_options), {  }, { class: 'form-select mt-1', required: :required }%>

        <%= f.label 'Langue', class: 'mt-1' %>
        <% languages_options = LanguageList::ALL_LANGUAGES.map { |l| ["#{l.iso_639_3} - #{l.name}", l.iso_639_3.upcase] }.append(['xxx - Unknown', 'xxx']) %>
        <%= f.select :code_language, languages_options, { include_blank: true }, { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1' }%>

        <%= f.label 'Version', class: 'mt-1' %>
        <%= f.select :version, (1..99), { selected: @resource.version }, { class: 'form-select mt-1', required: :required }%>

        <div class="ressource-translation d-none">
          <%= f.label 'Traduction', class: 'mt-1' %>
          <%= f.text_field :translation, class: 'form-control mt-1', minlength: 2, required: :required  %>
          <%= f.button :submit, class: 'btn btn-success mt-3' do %>
          <i class="fas fa-check"> Valider</i>
          <% end %>
        </div>
        <div class="ressource-upload">
          <%= f.label 'Fichier', class: 'mt-1' %>
          <%= f.file_field :file, class: 'form-control mt-1', required: :required %>
          <%= f.button :submit, class: 'btn btn-success mt-3' do %>
          <i class="fas fa-check"> Valider</i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/resources/show.erb
<div class="row justify-content-md-center">
  <div class="col-lg-8 col-md-12">
    <div class="alert alert-primary border my-4" role="alert">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item"><%= link_to 'Administration', admin_index_path %></li>
          <li class="breadcrumb-item"><%= link_to 'Ressources', admin_resources_path %></li>
          <li class="breadcrumb-item "><%= @resource.slug %></li>
        </ol>
      </nav>
    </div>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-lg-5 col-md-6">
    <div class="card mb-5">
      <h5 class="card-header">Ressource</h5>
      <div class="card-body">

        <form>
          <%= label :resource, 'Identifiant', class: 'mt-1' %>
          <%= text_field :resource, :slug, class: 'form-control mt-1', required: :required, minlength: 2, maxlength: 2, readonly: :readonly %>

          <%= label :resource, 'Étiquette', class: 'mt-1' %>
          <%= text_field_tag :label, @resource.label.name, class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Projet', class: 'mt-1' %>
          <%= text_field_tag :projet, @resource.projet.try(:name), class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Catégorie', class: 'mt-1' %>
          <%= text_field_tag :projet, @resource.category.try(:name), class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Format', class: 'mt-1' %>
          <%= text_field_tag :projet, @resource.format.try(:name), class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Langue', class: 'mt-1' %>
          <%= text_field :resource, :code_language, class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Identifiant', class: 'mt-1' %>
          <%= text_field :resource, :code_number, class: 'form-control mt-1', readonly: :readonly  %>

          <%= label :resource, 'Version', class: 'mt-1' %>
          <%= text_field :resource, :version_formatted, class: 'form-control mt-1', readonly: :readonly  %>

          <% unless @resource.translation.blank? %>
            <%= label :resource, 'Traduction', class: 'mt-1' %>
            <%= text_field_tag :projet, @resource.translation, class: 'form-control mt-1', readonly: :readonly  %>
          <% end %>

          <%= link_to edit_admin_resource_path(@resource), class: 'btn btn-warning mt-3' do %>
            <i class="fas fa-pencil-alt"> Modifier</i>
          <% end %>
        </form>
      </div>
    </div>
  </div>
</div>