config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'resources#index'
  get 'presentation', to: 'pages#presentation'
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :admin, only: [:index]
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :edit, :update, :new, :create]
    resources :projets, only: [:index, :show, :edit, :update, :new, :create]
    resources :categories, only: [:index, :show, :edit, :update, :new, :create]
    resources :formats, only: [:index, :show, :edit, :update, :new, :create]
    resources :resources, only: [:index, :show, :edit, :update, :new, :create]
  end
  resources :resources, only: [:index]
  resources :resources, only: [:show], param: :slug
  resources :qrcodes, only: [:show], param: :slug
  resources :qrcodes, only: [:index]
end

app/views/resources/index.erb
<div class="row justify-content-md-center my-4">
  <div class="col-lg-12 col-md-12">
    <%= form_with(model: @resource, remote: true, url: {controller: 'resources', action: 'index'}, html: { method: 'GET' }, id: 'index-search-engine') do |f| %>
    <div class="card">
      <h5 class="card-header">Moteur de recherche</h5>
      <div class="card-body">
        <div class="row">
          <div class="col-6 col-lg">
            <%= f.label 'Projet', class: 'mt-1' %>
            <%= f.select :projet_id, Projet.order(:name).all.map {|p| [p.name, p.id] }, { include_blank: true }, { class: 'form-select mt-1'}%>
          </div>
          <div class="col-6 col-lg">
            <%= f.label 'Mot', class: 'mt-1' %>
            <%= f.select :label_id, Label.order(:name).all.map {|l| [l.name, l.id] }, { include_blank: true} , { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1 rounded'}%>
          </div>
          <div class="col-6 col-lg">
            <%= f.label 'Catégorie', class: 'mt-1' %>
            <%= f.select :category_id, Category.order(:name).all.map {|c| [c.name, c.id] }, { include_blank: true }, { class: 'form-select mt-1' }%>
          </div>
          <div class="col-6 col-lg">
            <%= f.label 'Format', class: 'mt-1' %>
            <% formats_options = Format.order(:group).distinct.pluck(:group).map { |g| [g, Format.where(group: g).map {|fo| [fo.name, fo.id, {'data-code': fo.code, selected: fo.id == @resource.format_id }] }] } %>
            <%= f.select :format_id, grouped_options_for_select(formats_options), { include_blank: true }, { class: 'form-select mt-1' }%>
          </div>
          <div class="col-12 col-lg">
            <%= f.label 'Langue', class: 'mt-1' %>
            <% @resource.code_language = '' %>
            <% languages_options = LanguageList::ALL_LANGUAGES.map { |l| ["#{l.iso_639_3} - #{l.name}", l.iso_639_3.upcase] }.append(['xxx - Unknown', 'xxx']) %>
            <%= f.select :code_language, languages_options, { include_blank: true }, { 'data-live-search': 'true', 'data-style': 'btn-white', class: 'selectPicker border w-100 mt-1' }%>
          </div>
        </div>
        <% if current_user && current_user.admin? && @resources.present? %>
          <%= link_to qrcodes_path(ids: @resources.map(&:id), format: :zip), class: 'btn btn-info mt-3' do %>
            <i class="fas fa-qrcode"> QR</i>
          <% end %>
        <% end %>
      </div>
    </div>
    <% end %>

    <div class="row">
      <% @resources.each do |resource| %>
      <div class="col-lg-2 col-md-3 col-sm-4 py-3 align-self-center">
        <div class="card resources-thumb-card">
          <%= link_to resource_path(resource.slug) do %>
          <% if resource.translation %>
          <h5 class="card-text text-center resources-thumb-header align-items-center d-flex justify-content-center m-0 bg-light text-dark">
            <i class="fa fa-language pe-2"> <span class="resources-thumb-header-display"><%= resource.translation %></span></i>
          </h5>
          <% elsif resource.format.try(:group) == 'Sons' %>
          <h5 class="card-text text-center resources-thumb-header align-items-center d-flex justify-content-center m-0 bg-light text-dark">
            <i class="fa fa-volume-up pe-2"> <span class="resources-thumb-header-display"><%= resource.label.name %></span></i>
          </h5>
          <% else %>
          <%= image_tag url_for(resource.file), class: 'card-img-top resources-thumb-img m-0' %>
          <% end %>
          <% end %>

          <ul class="list-group list-group-flush">
            <li class="list-group-item resources-thumb-card-slug"><%= resource.slug.truncate(38) %></li>
          </ul>
        </div>
      </div>
      <% end %>
    </div>
    <% if @resources.empty? %>
    <div class="alert alert-secondary mt-3" role="alert">
      Désolé mais aucun résultat ne correspond à cette recherche.
    </div>
    <% else %>
    <div class="my-4">
      <%== pagy_bootstrap_nav(@pagy) %>
    </div>
    <% end  %>

  </div>
</div>

app/views/resources/show.erb
<div class="row justify-content-md-center mt-2">
  <div class="col-lg-6">
    <div class="alert alert-primary border mt-4" role="alert">

  <ol class="breadcrumb m-0">
    <li class="breadcrumb-item"><%= link_to :back do  %><i class="fas fa-arrow-circle-left pe-1"></i> Retour<% end %></li>
  </ol>
</div>
    <div class="card">
      <h5 class="card-header"><%= @resource.slug %></h5>
      <div class="row align-items-center">
        <div class="col-6">
          <% if @resource.translation %>
            <h5 style="height: 420px" class="card-text align-items-center d-flex justify-content-center m-0 bg-light text-dark text-center">
              <i class="fa fa-language pe-2"> <span class="resources-thumb-header-display"><%= @resource.translation %></span></i>
            </h5>
          <% elsif @resource.format.try(:group) == 'Sons' %>
          <h5 style="height: 420px" class="card-text align-items-center d-flex justify-content-center m-0 bg-light text-dark text-center">
            <i class="fa fa-volume-up pe-2"></i> <%= @resource.label.try(:name) %>
          </h5>
          <% else %>
            <%= image_tag url_for(@resource.file), class: 'card-img-top resource-img m-0' %>
          <% end %>
        </div>
        <div class="col-6 py-3">
          <div>

            <h3><%= @resource.label.try(:name).capitalize %></h3>
            <p class="mb-1">Projet: <%= @resource.projet.try(:name) %></p>
            <p class="mb-1">Catégorie: <%= @resource.category.try(:name) %></p>
            <p class="mb-1">Format: <%= @resource.format.try(:name) %></p>
            <p class="mb-1">Mot: <%= @resource.label.try(:name) %></p>
            <p class="mb-1">Numéro: <%= @resource.code_number %></p>
            <p class="mb-1">Version: <%= @resource.version_formatted %></p>
            <p class="mb-1">Langue: <%= @resource.code_language.upcase %></p>
            <p class="mb-1">Dernière modification: <%= time_ago_in_words @resource.updated_at %></p>
            <% if @resource.format.try(:group) == 'Sons' %>
              <audio controls src="<%= url_for(@resource.file) %>" class="mt-2 w-100 pe-4"></audio>
            <% end %>

            <div class="mt-2">
              <% if @resource.file.present? %>
                <%= link_to rails_blob_path(@resource.file, disposition: "attachment"), class: 'btn btn-success mt-2 me-1' do %>
                  <i class="fas fa-download"> Télécharger</i>
                <% end %>
              <% end %>
              <%= link_to qrcode_path(slug: @resource.slug, format: :png), class: 'btn btn-info mt-2 me-1 d-none d-sm-inline-block' do %>
                <i class="fas fa-qrcode"> QR</i>
              <% end %>
              <% if current_user && current_user.admin? %>
                <%= link_to edit_admin_resource_path(@resource), class: 'btn btn-warning mt-2' do %>
                  <i class="fas fa-pencil-alt"> Modifier</i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>