config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'resources#index'
  get 'presentation', to: 'pages#presentation'
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resources :admin, only: [:index]
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :labels, only: [:index, :show, :edit, :update, :new, :create]
    resources :projets, only: [:index, :show, :edit, :update, :new, :create]
    resources :categories, only: [:index, :show, :edit, :update, :new, :create]
    resources :formats, only: [:index, :show, :edit, :update, :new, :create]
    resources :resources, only: [:index, :show, :edit, :update, :new, :create]
  end
  resources :resources, only: [:index]
  resources :resources, only: [:show], param: :slug
  resources :qrcodes, only: [:show], param: :slug
  resources :qrcodes, only: [:index]
end

app/views/layouts/_header.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BDP</a>
    <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to 'Moteur de recherche', resources_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/presentation">Présentation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Tutoriel</a>
        </li>
        <% if current_user %>
        <% if current_user.admin %>
        <li class="nav-item">
          <%= link_to 'Ajouter une ressource', new_admin_resource_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Administration', admin_index_path, class: 'nav-link' %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <!-- <li><a class="dropdown-item" href="#">Action</a></li>
            <li><hr class="dropdown-divider"></li>-->
            <li>
              <%= link_to 'Déconnexion', sessions_path, class: 'dropdown-item', method: 'delete' %>
            </li>
          </ul>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to 'Inscription', new_user_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Connexion', new_sessions_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BDP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>

    <% if Rails.env.production? %>
      <script defer data-domain="bdp.fable-lab.com" src="http://plausible.fable-lab.com/js/plausible.js"></script>
    <% end %>
  </body>
</html>